services:
  - type: web
    name: meio-ambiente-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: meio-ambiente-db
          property: connectionString

databases:
  - name: meio-ambiente-db
    plan: free
